<?php

return array (
  'name' => 'www.demo.com',
  'beian' => 'Copyright ©  | www.demo.com',
  'cdnurl' => '',
  'version' => '2022-5-22 16:16:07',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    ' Request A Quote ' => 'Contact-us.html',
  ),
  'fixedpage' => 'cms/archives',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.ym.163.com',
  'mail_smtp_port' => '994',
  'mail_smtp_user' => 'info@zjszjs.com',
  'mail_smtp_pass' => 'Admin123456',
  'mail_verify_type' => '2',
  'mail_from' => 'info@zjszjs.com',
  'email' => '913083812@qq.com',
  'autosend' => '0',
  'title' => 'www.demo.com',
  'keywords' => 'www.demo.com',
  'description' => 'Invess offers an extensive range of professional services and a high degree of spe-cialization. We serves both private & public traded companies. We bring over 35 years of experience.',
  'logotxt' => 'Demo',
  'logo' => '',
  'logo2' => '',
  'head' => '1',
  'indexfw' => '1',
  'indexfl' => '1',
  'indexcp' => '1',
  'indexfdc' => '1',
  'sousuo' => '1',
  'indexxm' => '1',
  'footimg' => '',
  'map' => '',
  'banner' => '0',
  'ico' => '*****',
);
